<a href="https://colab.research.google.com/github/surakshyakarkii/MTA-Bus-Speeds-Analysis/blob/main/MTA_Team_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
# Download GitHub repository
!git clone https://github.com/surakshyakarkii/MTA-Bus-Speeds-Analysis.git

fatal: destination path 'MTA-Bus-Speeds-Analysis' already exists and is not an empty directory.

In [16]:
# Search ZIP files
for folder, subfolders, files in os.walk("MTA-Bus-Speeds-Analysis"):
    for file in files:
        if file.endswith(".zip"):
            print(os.path.join(folder, file))

MTA-Bus-Speeds-Analysis/MTA_Central_Business_District_Bus_Speeds__Beginning_2023_20260929.zip

In [17]:
# Import ZIP library
import zipfile
# Import file search
import glob
# Find ZIP file
zip_files = glob.glob("MTA-Bus-Speeds-Analysis/MTA_Central_Business_District_Bus_Speeds__Beginning_2023_20260929.zip", recursive=True)
# Open ZIP file
with zipfile.ZipFile(zip_files[0], "r") as zip_ref:
    zip_ref.extractall("/content/mta_data") # Extract dataset files

print("Dataset extracted successfully!")

Dataset extracted successfully!

In [18]:
import pandas as pd
import glob

csv_files = glob.glob("/content/mta_data/**/*.csv", recursive=True) # Find CSV files

df = pd.read_csv(csv_files[0]) # Load CSV data

df.head()

,Month,Day Type,Hour of Day,TIme Period,Route Type,Route ID,CBD Relation,Sum Mileage,Sum Time,Average Road Speed
0,12/01/2025,Weekday,0,Overnight,Express,BM1,Non-CBD,53.79,4.26,12.63
1,12/01/2025,Weekday,0,Overnight,Express,BM2,CBD,289.33,22.25,13.01
2,12/01/2025,Weekday,0,Overnight,Express,BM2,Non-CBD,135.75,13.24,10.25
3,12/01/2025,Weekday,0,Overnight,Express,BM3,CBD,102.76,4.49,22.86
4,12/01/2025,Weekday,0,Overnight,Express,BM3,Non-CBD,93.69,7.06,13.27

In [19]:
print("Rows and columns:", df.shape)# Show dataset size
df.info()

Rows and columns: (670748, 10)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 670748 entries, 0 to 670747
Data columns (total 10 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Month               670748 non-null  object
 1   Day Type            670748 non-null  object
 2   Hour of Day         670748 non-null  int64
 3   TIme Period         670748 non-null  object
 4   Route Type          670748 non-null  object
 5   Route ID            670748 non-null  object
 6   CBD Relation        670748 non-null  object
 7   Sum Mileage         670748 non-null  object
 8   Sum Time            670748 non-null  float64
 9   Average Road Speed  670748 non-null  float64
dtypes: float64(2), int64(1), object(7)
memory usage: 51.2+ MB

In [20]:
df["Sum Mileage"].head(10) # Preview mileage values

0     53.79
1    289.33
2    135.75
3    102.76
4     93.69
5     67.83
6    204.92
7     77.60
8    242.56
9     32.38
Name: Sum Mileage, dtype: object

In [22]:
# Convert mileage numbers
df["Sum Mileage"] = pd.to_numeric(
    df["Sum Mileage"].str.replace(",", ""),
    errors="coerce"
)

In [23]:
print(df["Sum Mileage"].dtype) # Check mileage type
print(df["Sum Mileage"].isnull().sum()) # Check missing values

float64
0